[[build]]
  command = "npm run build"
  publish = "/build"
  base = "/"

# The following redirect is intended for use with most SPAs 
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
